# All configurable constants — edit here to tune the simulation

GRID_ROWS = 20
GRID_COLS = 20
CELL_SIZE_PX = 36  # Pixels per cell in the GUI canvas
NUM_DRONES = 5
TICK_INTERVAL_MS = 300  # Simulation tick in milliseconds (GUI timer)

# Battery
BATTERY_MAX = 100.0
BATTERY_DRAIN_PER_MOVE = 2.0
BATTERY_DRAIN_COMM_RELAY = 0.5
BATTERY_RECHARGE_RATE = 5.0
LOW_BATTERY_THRESHOLD = 20.0

# A* cost weights
COST_DISTANCE = 1.0
COST_ENERGY = 0.5
COST_RISK_BLOCKED = 9999
COST_RISK_AFFECTED = 2.0
COST_RISK_HIGH_PRIORITY = 0.1  # Incentivize going there (low cost)
COST_COMM_PENALTY = 3.0

# Genetic Algorithm
GA_POPULATION_SIZE = 50
GA_GENERATIONS = 30
GA_CROSSOVER_PROB = 0.7
GA_MUTATION_PROB = 0.2
GA_TOURNAMENT_SIZE = 3
FITNESS_WEIGHT_COVERAGE = 0.4
FITNESS_WEIGHT_PRIORITY = 0.3
FITNESS_WEIGHT_EFFICIENCY = 0.2
FITNESS_WEIGHT_RISK = 0.1

# Q-Learning
QL_ALPHA = 0.1  # Learning rate
QL_GAMMA = 0.9  # Discount factor
QL_EPSILON_START = 1.0  # Exploration rate start
QL_EPSILON_END = 0.05
QL_EPSILON_DECAY = 0.995
QL_REWARD_HIGH_PRIORITY = 100
QL_REWARD_AFFECTED = 30
QL_REWARD_COMM_GOOD = 20
QL_REWARD_EFFICIENT_BATTERY = 15
QL_PENALTY_BLOCKED = -100
QL_PENALTY_COMM_LOST = -40
QL_PENALTY_BATTERY_DRAIN = -20

# Dynamic events
EVENT_INTERVAL_TICKS = 15  # Every N ticks, a random disaster event fires
FLOOD_SPREAD_PROB = 0.3
FIRE_BLOCK_PROB = 0.2
COMM_DECAY_PROB = 0.25

# FastAPI backend
API_HOST = "127.0.0.1"
API_PORT = 8000
